### ISSUE TITLE
Different order of require statements causes different behavior

### ISSUE THREAD

**Issue by ivan-nikitovic** [stealjs/steal#519] opened 2015-11-24 16:09 UTC
I am getting error 'undefined is not an object (evaluating 'b.dependencies[c].value'), at [this line](https://github.com/stealjs/steal/blob/master/steal.js#L1749). 

Dependencies array simple gets undefined as one of the elements. 

Changing order of require statements and making ```require('./view.stache!)``` the last require statement in the file solves the problem, but it's weird, because order of require statements should not affect application behavior, especially having in mind that all requires are put on the top of the file. 

This gives error
```
var e1 = require('bar/foo/e1');
var view = require('./view.stache!');
var e2 = require('bar/foo/e2');
```
The empty element in dependencies array is  ```require('./view.stache!')```.  So we get [here](https://github.com/stealjs/steal/blob/master/steal.js#L1749) undefined is not an object error. 

but this works:
```
var e1 = require('bar/foo/e1');
var e2 = require('bar/foo/e2');
var view = require('./view.stache!');
```

Does anyone have any idea why is this happening?

**Comment by justinbmeyer** [comment] 2015-11-24 19:42
Do you have a cycle? ModuleA depends on ModuleB that depends on ModuleA.

**Comment by ivan-nikitovic** [comment] 2015-11-26 12:42
No, there are no loops. 

I have just made one, to see how app behaves with the loop, and nothing similar is happening. So I guess that, that's not the problem. 

Any other guess?

**Comment by justinbmeyer** [comment] 2015-11-26 14:32
Can you make a small example where this happens?

**Comment by asvetlenko** [comment] 2015-12-08 11:46
We find the same problem only in safari browsers as for last iOS safari and with windows safari too.

we try to move .stache templates to end of the dependencies list but it could not help us. Also we tried to write full path to .stache template and it could not helped us. And the last step that could help us it writing full path to all .js files and it eventually resolved problem with stealjs.

So for resolving problem with stealjs in safari browsers you should write only full path to js and .stache files

**Comment by justinbmeyer** [comment] 2015-12-08 13:54
Can you please create an example. We want to fix this, but have never seen it.

**Comment by pYr0x** [comment] 2016-06-12 00:31
cant reproduce this. need more info from the OP

**Closed by pYr0x** 2016-06-12 00:31 UTC
Labels: bug
