### ISSUE TITLE
peerDependencies are not correctly checked for matching parent packages

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#555] opened 2016-01-17 23:57 UTC
NPM 2.
An app has the same dependecy as installed module (so module does not install it in it's node_modules). 
app's package.json:
```
"rx": "^4.0.7"
```
module's package.json:
```
"rx": "^4.0.6"
```

Steal tries to load it from `module/node_modules/rx/package.json` and breaks.

If to chnage app's package.json:to `"rx": "^4.0.6"` it start to works.

**Comment by matthewp** [comment] 2016-01-19 13:50
Will need a test or something for this.

**Comment by whitecolor** [comment] 2016-01-19 14:29
I say you what is going on. That is bug.

**Comment by matthewp** [comment] 2016-01-19 14:48
This is not specific enough for me to do anything about. Can you at least give me the name of a module that depends on rx `^4.0.6` so that I can simulate the bug?

**Comment by whitecolor** [comment] 2016-01-19 17:53
of cource just install https://github.com/cyclejs/cycle-storage-driver
`npm install rx`(sould be "rx": "^4.0.7")
`npm install @cycle/core @cycle/storage' (storage has "rx": "^4.0.6" dependency, should not install)

Try to require both.

**Comment by matthewp** [comment] 2016-01-19 18:54
Thanks, so the issue is not that the app's package.json is the same as the deps. It's that there's a third module (@cycle/core in this case) that has a peerDependency of *.  We're not handling this correctly.  I'll update the title.

**Comment by matthewp** [comment] 2016-01-19 18:54
By the way, in my test this doesn't prevent the app from loading correctly, but does cause one 404.

**Comment by matthewp** [comment] 2016-01-19 19:31
Have a fix in https://github.com/stealjs/system-npm/pull/96, will get this in a patch release.

**Comment by matthewp** [comment] 2016-01-19 19:56
Reopening until it is released.

**Comment by matthewp** [comment] 2016-01-19 20:21
This is fixed in 0.13.2

**Closed by matthewp** 2016-01-19 20:21 UTC
