### ISSUE TITLE
Bundle loading performance issue on Android

### ISSUE THREAD

**Issue by isadovskiy** [stealjs/steal#742] opened 2016-06-08 20:21 UTC
Hello.

I see noticeable performance issues on Android Chrome while loaded bundle registers the modules it contains.

Here is the URL to play: http://tiny.cc/vvn2by

On Desktop Chrome, timeline looks like: http://take.ms/xJuYp. As I understand, during this phase steal resolves the dependencies stored in bundle and registers the modules. On the desktop it takes 600-800ms.

In Android Chrome the picture is different: http://take.ms/8cinec. It takes more than 2 seconds to resolve and register the dependencies.

Per my understanding, nothing special happens during this phase. Code from modules is not executed. It just builds the dependency's tree... So wondering why it;s so slow and if there is a way to speed up it on Android?

**Comment by isadovskiy** [comment] 2016-06-08 21:41
I think the possible reason is every dependency is resolved within its own tick. So there are idles between ticks Which results additional initialization delays. At least during first phase, which looks too fragmented on the profile screen shot.

**Comment by pYr0x** [comment] 2016-06-11 19:02
@isadovskiy thanks for investigating but i cant follow the problem... where is the problem exactly? and how can we fix it?

**Comment by isadovskiy** [comment] 2016-06-11 21:01
So the problem is on Android it takes 2+ seconds just to execute code inside bundled JS, which does nothing except registering modules and their dependencies...

**Comment by isadovskiy** [comment] 2016-06-12 11:48
@pYr0x, @matthewp so here are our findings. In stealjs there is a code which detects the best way to do async scheduling to resolve next dependency: https://github.com/stealjs/steal/blob/master/steal.js#L229

We replaced it with sync function call to process next dependency and got 10x (!!!) performance on Android. For desktop, we also found noticeable performance increase (about 3-4 times) for this phase.

So wondering why we need to process dependencies in async way in production bundle? Also wondering why we need to implement async scheduling at all - since in dev mode everything is loaded via ajax already in async way...

So can we eliminate this async scheduling code at least for production? Or at least have configuration option, which allows to process the dependencies in sync way?

**Comment by kirylandruski** [comment] 2016-06-12 13:39
@pYr0x we've just added `    var asap = function (f) { return f(); }; ` line before return statement (https://github.com/stealjs/steal/blob/master/steal.js#L243) for debug purposes

**Comment by isadovskiy** [comment] 2016-06-20 11:08
Looks like the fix mentioned above by @kirylandruski breaks the loading. @matthewp do you have any sugegstions how to improve/work it around?

**Comment by matthewp** [comment] 2016-06-20 11:42
@isadovskiy Not particularly, no. Steal does use a lot of Promises (the async scheduling you referred to) but that shouldn't matter in regard to load time by very much, certainly not to see the results you are getting. My first question would be: are you using progressive loading (with more than 1 bundle) ?  If not, you probably should be, this would prevent it from loading a very large bundle that must execute the entire tree all at once.

**Comment by isadovskiy** [comment] 2016-06-20 14:44
@matthewp, yes at the moment evething is bundled within the single JS file. We are working ni split it no multiple (page-based) smaller bundles.

But in general, initializaing modues stored inside ~300Kb gzipped single bundle for several seconds sounds like unacceptable value for production environment. So I'm really interested in the fix. Please let me know how I can help you to reproduce the issue. Or point me to the code so we could do further research.

To my mind, the issue is not in promises itself, but with their resolvation via async timeouts (https://github.com/stealjs/steal/blob/master/steal.js#L229) - via nextTick, setTimeout or munation observer. It could be idle time between ticks, whch increses the whole processing time. On android pases between ticks could be more noticable.

**Comment by SergeRNR** [comment] 2016-07-22 15:12
Hello.

We created a demo page where you can inspect JS profile of bundle evaluating.
Bundle contains main "app.js" file with 300 modules imported. Each module contains simple object literal with single string property.
In Chrome on Android the script is evaluated ~850-900 ms. [Screenshot](http://storage6.static.itmages.com/i/16/0722/h_1469200205_3161597_f2238a627d.png)

**Comment by matthewp** [comment] 2016-07-22 15:23
I wonder if this is caused by the Promise polyfill. Does the Android version you are testing support Promise natively? If so we could maybe create a build without the Promise polyfill and see if that helps.

**Comment by SergeRNR** [comment] 2016-07-22 15:43
Sure, Promise is supported in Chrome mobile 32+. I have latest installed (51). We could try a build without polyfill.

**Comment by matthewp** [comment] 2016-07-22 16:35
Ok, I don't have the bandwidth to create such a build for you, but it should be easy to do yourself. the Promise polyfill is at the top of steal.js, it ends here: https://github.com/stealjs/steal/blob/master/steal.js#L1270

So delete the first 1270 lines (or wherever it ends in your version) and then save it. Minify it as steal.production.js if you need steal.production.  Then do another build using this steal and see what you get.

**Comment by SergeRNR** [comment] 2016-07-25 08:29
Hi @matthewp ,
I removed Promise polyfill. The result is quite interesting:
- for 300 modules there is no remarkable difference,
- for 1k modules evaluating executes 10-20% slowly, on mobile device it takes 2.3-2.5 s VS 1.9-2.0 with polyfill.

**Comment by SergeRNR** [comment] 2016-07-27 12:30
Hi,

System JS SFX bundles give us a performance boost (800-1000 ms now for evaluating). If I understand right, the same functionality will be provided by steal-almond. When it will be ready to use? I tried the current version of steal-almond, it works and the final bundle is perfect - evaluated during 530 ms.

**Comment by matthewp** [comment] 2016-07-27 14:50
That's good to hear. steal-almond is ready to use if it's working for you. IIRC it has problems with can 2.3 in some scenarios, but I don't remember what those are. As long as you don't have any dynamic module loading, steal-almond makes sense to use since no run-time configuration is needed. It will be faster because it doesn't dynamically resolve names or do any of the Promise-based craziness normal Steal builds will do.

I would just be sure to thorough test that your app is working with it, as it's only been a side-project at this point.

**Comment by isadovskiy** [comment] 2016-07-28 10:10
@matthewp this is one issue with the build produced by steal-almond: it does not expose any public API to obtain modules bundled inside. 

In our scenario, all modules are bundled inside all.js and we are requiring them from different places in our HTML file using  `steal.import`. It is possible to provide same API for steal-almond bundle?

**Comment by matthewp** [comment] 2016-07-28 11:56
That's right, almond doesn't have any method for dynamically loading, that's what makes it so fast.  I would see if there's another way to avoid using `steal.import()` in your HTML, that's usually not needed in production. You could possibly create a different `main` that includes all of the code that's currently in your HTML.

**Comment by isadovskiy** [comment] 2016-07-28 12:38
It should not load anything dynamically. It should just allow to retrieve what's already loaded.

Our page consists of a set of independent modules, which presense on the page is configured via special admin interface; thus we can't predict which modules will be on the page and which initialization code we should put into single entry point.

So any reason to not allow to expose internal `require` method via `steal.import()` to retrieve already loaded and registered modules? It could be optional and configurable via some build parameter

**Comment by matthewp** [comment] 2016-07-28 13:02
steal.import() has another purpose, I think it would be weird to make it do something totally different if almond is being used. You can use the almond methods though, looks like they already expose a [synchronous require()](https://github.com/requirejs/almond/blob/master/almond.js#L333) so you could try using that.

**Comment by isadovskiy** [comment] 2016-07-28 13:13
Looks like almond's `require()` method is not exposed. Thet are wrapped inside anonymous function: http://take.ms/Gi9Hf

**Comment by matthewp** [comment] 2016-07-28 13:35
That's steal-almond's fault, it can be exposed. The logic is here: https://github.com/stealjs/steal-almond/blob/master/main.js#L44-L48  try setting `window.require` maybe.

**Comment by matthewp** [comment] 2017-05-31 20:30
Just an update here. We are actively working on steal's production performance as part of the new slim loader: https://github.com/stealjs/steal-tools/issues/661 . You can think about this as being similar to steal-almond, but smaller and with more features like progressive loading.

**Comment by isadovskiy** [comment] 2017-06-02 10:59
Great news @matthewp ! We will be waiting for release

**Comment by matthewp** [comment] 2017-08-30 17:10
So sorry I never followed up, but this was released a while back. It would be cool if your team could start using this. Would you like some help getting this set up?

**Comment by isadovskiy** [comment] 2017-09-09 08:11
@matthewp do you have any instructions how to setup and configure it to start using/testing?

**Comment by matthewp** [comment] 2018-10-12 12:05
Yep, here: https://stealjs.com/docs/StealJS.optimized-builds.html

**Comment by chasenlehara** [comment] 2018-11-14 15:19
Closing this because the optimized build should help; @isadovskiy please feel free to reopen or create a new issue if not. 😊

**Closed by chasenlehara** 2018-11-14 15:19 UTC
Labels: bug, performance, production
