### ISSUE TITLE
npmAlgorithm "flat" does not work with namespaced modules

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#564] opened 2016-01-26 21:29 UTC
Having this such deps does not work for `flat`
```
"@cycle/core": "^6.0.0",
"@cycle/dom": "^8.1.0",
"@cycle/http": "^7.0.0",
```
with npm2 works ok.

**Comment by whitecolor** [comment] 2016-01-26 21:30
BTW steal and can too could use this approach for related modules

**Comment by whitecolor** [comment] 2016-02-17 21:19
Would be great to fix.

**Comment by whitecolor** [comment] 2016-03-17 12:51
It seem to work actually now, if no problems will be found will colose it shortly.

**Comment by whitecolor** [comment] 2016-05-22 16:30
What about this?
Error actual is something like this:
```
moduleName.split is not a function
    at Object.utils.moduleName.parse (http://localhost:6666/node_modules/steal/ext/npm-utils.js:149:33)
```

**Comment by matthewp** [comment] 2016-05-22 17:04
OK I'll take a look this week.

**Comment by matthewp** [comment] 2016-06-07 12:06
I'm unable to reproduce this bug (namespaced modules).  I created a [demo project](https://gist.github.com/matthewp/1f499a77e2878fc41f9c1e2701bd4720) that loads those modules.  There isn't a problem with loading them from a flat file structure.

However there is another bug which I've opened here: https://github.com/stealjs/steal/issues/731

Because these modules are depending on a global `Buffer` constructor. 

Closing, if you can provide a breaking example I'll reopen.

**Closed by matthewp** 2016-06-07 12:06 UTC
Labels: bug
