### ISSUE TITLE
'live-reload' as configDependency breaks generated plugin build

### ISSUE THREAD

**Issue by nlundquist** [stealjs/steal#621] opened 2016-03-09 15:27 UTC
Using the newest version of donejs, generate a plugin:
`donejs init --type plugin` 

Once that is complete (answers to prompts unimportant) try to build the plugin:
`donejs build`

This will fail with the error:
```shell
Nilss-MBP:new-plugin nlundqu$ npm run build

> new-plugin@0.0.0 build /Users/nlundqu/Repos/new-plugin
> node build.js

OPENING: /Users/nlundqu/Repos/new-plugin/package.json!npm
OUTPUT: +cjs
OUTPUT: +amd
OUTPUT: +global-js
> /Users/nlundqu/Repos/new-plugin/dist/cjs/new-plugin.js
> /Users/nlundqu/Repos/new-plugin/dist/amd/new-plugin.js
> /Users/nlundqu/Repos/new-plugin/dist/global/new-plugin.js
Potentially unhandled rejection [1] ReferenceError: window is not defined
    at setup (file:/Users/nlundqu/Repos/new-plugin/node_modules/steal/ext/live-reload.js:243:38)
    at tryCatchReject (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:821:13)
    at Scheduler._drain (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:97:19)
    at Scheduler.drain (/Users/nlundqu/Repos/new-plugin/node_modules/steal/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:62:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

This can be worked around by removing the 'live-reload' configDependency from the system config in package.json.

However, the unfortunate fact remains that the released generator is creating plugins that can't be built.

**Comment by matthewp** [comment] 2016-03-09 15:43
Thanks, I know the cause (sort of), will add a test to steal-tools.

**Comment by matthewp** [comment] 2016-03-09 15:46
Since this a build issue, moving it to https://github.com/stealjs/steal-tools/issues/395

**Closed by matthewp** 2016-03-09 15:46 UTC
