### ISSUE TITLE
base-url tag attribute tries to loads stealconfig

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#395] opened 2015-04-15 21:20 UTC
I want to set baseURL using tag attribute:
`<script src="../node_modules/steal/steal.js" data-base-url="base" data-main="app"></scirpt>`

If I do so it tries to load base\stealconfig.js (I dont' have any) and doesn't try to load package.json.
 
I tried to add data-config="../package.json!npm" in script tag, but it doesn't load system config. 

And with data-base-url it tries to load main="app" from / app.js not /base/app.js

original issue in steal-tools with some comments:
https://github.com/stealjs/steal-tools/issues/222#issuecomment-93561955

**Comment by matthewp** [comment] 2015-04-16 19:43
Have you tried using directories.lib?  It fits better with the way npm works.  Look at the docs towards the bottom here: http://stealjs.com/docs/npm.html  Instead of using baseURL you can set a directories.lib and that is the "base" for your code.  This might prevent you from needing to use it in dev.  Let me know.

**Comment by whitecolor** [comment] 2015-04-16 22:39
No this doesn't work for me. Without base URL it tries to resolve modules from the root. I didn't noticed that "directories.lib" affected anything.

**Comment by matthewp** [comment] 2015-04-16 22:41
If you add this to your package.json:

```json
{
  "system": {
    "directories": {
      "lib": "base"
    }
  }
}
```

It will load your own code from `base`. Why does this not work?

**Comment by whitecolor** [comment] 2015-04-16 22:41
Well no it does not.

**Comment by whitecolor** [comment] 2015-04-16 22:44
`<script src="../node_modules/steal/steal.js" data-main="app-dev"></script>` first tries to load `app-dev` from `/` then I change `data-main="base/app-dev`, 

in app dev:
```
require('my-module/some')
```
it tries to load `/my-module/some.js` not `/base/my-module/some.js`

**Comment by matthewp** [comment] 2015-04-16 22:49
You don't need a main when using the npm extension.  What you probably want is something like:

```json
{
  "name": "my-module",
  "main": "app-dev",
  "system": {
    "directories": {
      "lib": "base"
    }
  }
}
```

```html
<script src="../node_modules/steal/steal.js"></script>
```

Then in your app-dev you can do `require('my-module/some')` and it will load the correct file.

We have lots of tests for this so we know it works.  Here's one example you might want to test out: https://github.com/bitovi-components/bit-tabs

If you can provide a breaking test that would help resolve what the problem is, maybe some other option is interfering.

**Comment by whitecolor** [comment] 2015-04-16 22:54
I have `main` for `dev` mode (were I init some dev stuff) and another import `application main` (wich is used is `main` for build (production).

I don't want to put `main` in package json.

I don't get my `name` field in package.json should be `my-module`, I have 100s app modules that I require like requre('my-module') or require('components/my-comp').

**Comment by matthewp** [comment] 2015-04-16 22:58
Ok, you can put your main in your script tag if you want. But you should include the package name in the main's name, for example if your package name is `my-module` you want:

```html
<script src="../node_modules/steal/steal.js" main="my-module/app-dev"></script>
```

This will load app-dev from the correct place.

**Comment by whitecolor** [comment] 2015-04-16 23:00
I did this:
> data-main="base/app-dev,

it doesn't load other modules from /base ever `directories.lib` set to "base"

**Comment by matthewp** [comment] 2015-04-16 23:02
It shouldn't be `base/app-dev`.  You should never include `base` if you're using `directories.lib`. Using `directories.lib` sets the starting point when importing npm packages. Instead you need to include the package name.  What is your package name?

**Comment by whitecolor** [comment] 2015-04-17 04:09
BTW currelty I have the following strucutre

/client/ 
   .... all client app here
/server
/package.json - common package.json for server deps and system config

Maybe you would recommend:

/client/ 
   .... all client app code here
   /index.html - dev mode index
   /package.json - package.json with client deps and system config
/server
/package.json - package.json for server

In this case `base-url` works in such case:
```HTML
<script src="node_modules/steal/steal.js" data-main="app-dev" base-url="client" config="client/package.json!npm"></script>
```

Second variant is nice in terms of separation of deps configs, the problem with secound variant how to share common npm packages.

**Comment by matthewp** [comment] 2015-04-17 16:32
I would recommend the second variant, probably even have them in separate repositories. There is no issue with sharing common deps, you can (and probably should) have dependencies specific to client and server. What happens if you need to upgrade `lodash` in the server for some feature but don't want to also do so in the client?  

However the first variant will work as well if that's what you prefer using the `directories.lib` feature.  directories.lib can be `client` and then you don't need to set the `config` or `base-url` properties at all.

Closing this for now, please reopen if you can provide a sample of `directories.lib` not working.

**Closed by matthewp** 2015-04-17 16:32 UTC
Labels: bug

**Comment by whitecolor** [comment] 2015-04-17 23:10
ok, thanks.

**Comment by whitecolor** [comment] 2016-04-15 14:50
I have follinwing structure

```
/
package.json
/client
  app.js
  module.js
  index.index
```

In my app.js:
```
import `module.js` // I want to be imported from /client/module.js
```

I tried to do
```json
    "directories": {
      "lib": "client"
    },
```
But it tries to load app.js and module.js from `root` not `client` didn't I get correctly what "directories" does?

**Comment by matthewp** [comment] 2016-04-15 14:55
`directories.lib` sets the root for a **package**. Change your code to `import 'packageName/module'` for it to work.

**Comment by whitecolor** [comment] 2016-04-15 14:58
I don't get what is a `package` and `packageName`

I want my modules be resolved without `import 'client/module'`, just import 'module' is it possible?

**Comment by matthewp** [comment] 2016-04-15 16:12
it's the package name in your package.json.  For example:

```
{
  "name": "app",
  "system": {
    "directories": {
      "lib": "client"
    }
  }
}
```

and then to use it:

```js
import 'app/module';
```

So prefix with `app/`.

> I want my modules be resolved without import 'client/module', just import 'module' is it possible?

There's the `baseURL` that changes your root. However, if you change your root to `client/` then it can't look up the node_modules (because they are now below the root).

I think what you want is to say "import everything *except* node_modules from this folder". However, this would mean you could never import anything below your `directories.lib` folder (except packages).

Some other people have wanted the same thing, so I'm open to it. I don't think we should change `directories.lib` as that's used for 3rd party libraries and does exactly what you want in that scenario.  But for apps maybe there could be a new option, `directories.app` or something that works the way you describe.

Feel free to add an issue for this.
