### ISSUE TITLE
Steal Errors about a total valid module name

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1324] opened 2018-01-29 07:43 UTC
Illegal module name "steal-socket.io@git+https://github.com/frank-dspeed/steal-socket.io.git#s2#index"
 
- at Loader.value steal/src/loader/loader-sans-promises.js:1948:19)
- at Loader.loader.normalize steal/main.js:3579:44
- at Loader.loader.normalize steal/ext/live-reload.js:103:20)
-  at createModuleNameAndNormalize steal/ext/npm-extension.js:251:25)

**Comment by pYr0x** [comment] 2018-01-29 11:56
how does your dependencies in your package.json file look like

**Comment by frank-dspeed** [comment] 2018-01-29 19:50
@pYr0x "steal-socket.io": "git+https://github.com/frank-dspeed/steal-socket.io.git#s2"

**Comment by BigAB** [comment] 2018-02-20 00:46
This issue prevents me from upgrading a project to the latest steal, because we have 3 packages in the project that are only available as git repos, not npm modules.

**Comment by frank-dspeed** [comment] 2018-02-20 07:18
@BigAB i have solved it i need to write more about it but in general it can handle git repos i have some gitrepos in my project and it works.

it was something diffrent but need to check my documentation

**Comment by matthewp** [comment] 2018-02-26 14:06
I tried to recreate in a gist and could not: https://gist.github.com/matthewp/aedb8eafce803363e3913dd339e39d45

What am I doing differently here?

**Comment by frank-dspeed** [comment] 2018-02-27 13:55
@matthewp you do nothing diffrent it probally don't happens with all modules i found at present no way to reproduce it also.
that leads me to the idea maybe it has something to do with the package.json and the main property

**Comment by BigAB** [comment] 2018-03-03 07:30
Here is an example of one dep that fails for me with this error:
`"gc-libs": "git+ssh://git@gitlab.sd.apple.com:gbi/gc-libs#v1.4.1",`

**Comment by BigAB** [comment] 2018-03-03 08:05
OK, so on further investigation this seems to not actually be a problem, though you actually want to call this a **problem with the error message**.

The problem comes from the fact whenever you do a single npm install like `npm install steal@latest` or something like that as opposed to a full install `npm install`, for whatever reason npm removes the git linked modules from `node_modules`. Why? No idea.

The real error was actually staring me in the face the whole time:
<img width="845" alt="image 2018-03-03 at 2 03 20 am" src="https://user-images.githubusercontent.com/76821/36931962-18efbce2-1e87-11e8-9266-c9c9bea523a3.png">

See that first error, that's what actually is happening, package.json can't be found because npm removed the module from my `node_modules` directory.

The second error about **`Illegal module name "gc-libs@git+ssh://git@gitlab.sd.apple.com:gbi/gc-libs#v1.4.1#flatten/flatten"`** is actually a red herring.

Perhaps we could address the confusing error message?

**Comment by matthewp** [comment] 2018-03-05 15:33
Yeah, for sure, so what are some steps to reproduce? Is this correct?

1. Do a full npm install.
2. Do a partial npm install `npm install foo@bar`, does it need to be one of these git linked module or any?
3. See the bad error.

**Comment by BigAB** [comment] 2018-03-05 15:39
Yes.
 Specifically I had only 2 deps, steal and a git linked one.
```js
// package.json
// ...
  "dependencies": {
    "gc-libs": "git+ssh://git@gitlab.sd.apple.com:gbi/gc-libs#v1.4.1",
    "steal": "^1.7.0"
  },
// ...
```
I did `npm i`
'npm i steal@latest`
`serve`

but of course, that's not going to work for you, you'll need a non-private git linked module... I wonder if that has anythign to do with it.

**Comment by matthewp** [comment] 2018-03-05 16:30
Cool, can try with a non-private git module pretty easily.

**Comment by matthewp** [comment] 2018-08-08 14:47
This is fixed in the 1.x branch. https://github.com/stealjs/steal/releases/tag/v1.12.5

Fix coming to master shortly.

**Closed** 2018-08-08 18:04 UTC
Labels: bug, npm

**Comment by matthewp** [comment] 2018-08-08 18:08
Part of https://github.com/stealjs/steal/releases/tag/v2.1.2
