### ISSUE TITLE
Babel does not export default

### ISSUE THREAD

**Issue by mihalycz** [stealjs/steal#566] opened 2016-01-28 13:27 UTC
Hello!

I have a simple test module.

``` javascript
export default function () {
	return 'Hello World!';
};
```
I set babel as a transpiller in package.json

``` javascript
  "dependencies": {
    "can": "^2.3.10",
    "jquery": "1.11.1",
    "steal": "^0.13.2"
  },
  "system": {
    "npmAlgorithm": "flat",
    "npmIgnore": [
      "devDependencies"
    ],
	"transpiler": "babel"
  }, 
``` 
And I see  the transpilled code like this

``` javascript
(function() { var __moduleName = "module"; var __moduleAddress = "http://localhost:63342/1/module.js";System.register([], function (_export) {
	'use strict';

	var func;
	return {
		setters: [],
		execute: function () {
			func = function func() {
				return 'Hello World!';
			};

			_export('func', func);
		}
	};
});
//# sourceMappingURL=data:application/json;base64,
 }).call(__global);
```
But if I use Babel Repl I receive

``` javascript
'use strict';

Object.defineProperty(exports, '__esModule', {
	value: true
});

exports['default'] = function () {
	return 'Hello World!';
};

;
module.exports = exports['default'];

```

**Comment by matthewp** [comment] 2016-01-28 23:28
What version is your babel repl? We're still on Babel5, upgrade to Babel6 is in progress but not finished.  Could be the reason.

**Comment by matthewp** [comment] 2016-02-01 20:10
Going to close, let me know if you still need help with this.

**Comment by isadovskiy** [comment] 2016-02-01 21:26
@matthewp, the problem is currently Steal behaves differently for dev and prod build when using babel is transpiller. To import module above in development mode, I should write

steal.import('my-module', function (module) { )

**Comment by matthewp** [comment] 2016-02-01 21:59
Yes, this is bug, we know.  It only happens in certain scenarios and I haven't been able to figure out what that scenario is, you can do a work around:

```js
steal.import('my-module', function (module) { 
  module = module.default || module;
  console.log(module.default());
});
```

Yes, this is terrible, and doesn't excuse the bug.  We are working out the interop problem in this bug: https://github.com/stealjs/steal/issues/551

Node.js is currently working on what their interop will be like, so we'll likely follow their lead.

**Comment by isadovskiy** [comment] 2016-02-01 22:40
We have minimalistic example. Can share if that's help.

**Comment by matthewp** [comment] 2016-02-01 23:08
Sure, please do.

**Comment by mihalycz** [comment] 2016-02-02 10:48
You can find example here:
https://github.com/mihalycz/canjs-stealjs-test

**Comment by matthewp** [comment] 2016-02-02 13:16
Thanks!

**Comment by whitecolor** [comment] 2016-02-02 13:35
@mihalycz you can use latest babel6 with precompilation on server side like it is done in https://github.com/whitecolor/can-hot

**Comment by matthewp** [comment] 2016-05-18 15:53
Not sure why I closed this, this needs to be looked at for 1.0

**Comment by daffl** [comment] 2016-05-18 15:58
Babel 6 does not set the default export anymore. For my server side modules I am using the [add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) plugin. But it's a little finicky since it only allows one export.

**Comment by matthewp** [comment] 2016-05-18 16:03
Ah ok, that's good to know. I'm thinking we'll follow this behavior.  So just need a bunch of tests to make sure it's doing the right thing now.

When the new [plugins API](https://github.com/stealjs/steal/issues/671) lands I'll likely build a babel steal plugin. This will be the path to use Babel plugins and the like.  This way still Steal has ES6+ support by default (using the babel/traceur versions we include) but you can use a Babel plugin instead which will be more up to date and provide the ability to also use external plugins, etc.

**Comment by isadovskiy** [comment] 2016-05-18 22:18
Great to know. Thanks for the update!

**Comment by matthewp** [comment] 2016-06-07 15:09
This is now working with the Babel 6 upgrade which is part of `1.0.0-pre.1`. I've submitted a PR to https://github.com/mihalycz/canjs-stealjs-test/pull/1 which shows this working. Closing.

**Closed by matthewp** 2016-06-07 15:09 UTC
