### ISSUE TITLE
Steal can't locate LESS files outside of main directory

### ISSUE THREAD

**Issue by jeroencornelissen** [stealjs/steal#856] opened 2016-10-06 09:46 UTC
When we run our tests with `donejs test`, steal can't locate LESS files outside of main directory.
We have some general LESS files with variables and mixins on a lower level in our directory structure.
Inside `styles.less` we do `@import “../../../../resources/styles/variables.less"`

If we do `donejs test`, testee starts up chrome and goes to http://localhost:3996/src/test.html
And steal tries to load `variables.less` like this: `http://../resources/styles/variables.less`, resulting in an error.

I think this is because testee starts a “server” inside the main folder, and our global less files are on a lower level.

Our project tree looks (kind of) like this:

- /httpdocs
  - /modules
    - /Profile
      - /desktop
        - /main
          - main.js
          - styles.less
          - package.json
          - /src
            - index.stache
  - /resources
    - /styles
      - variables.less

**Comment by matthewp** [comment] 2016-10-06 12:46
Hi, the problem is indeed what you suspect. Testee does start a local server to run your tests and since that file is outside of your project, it fails to load.

What I would recommend when you want to colocate styles is to use a symlink inside of your project that points to that variables.less.

**Comment by matthewp** [comment] 2016-10-06 14:19
Since this is unrelated to Steal I'm going to close it, but we can continue to discuss here, happy to help :)

**Closed by matthewp** 2016-10-06 14:19 UTC
Labels: question

**Comment by jeroencornelissen** [comment] 2016-10-09 19:19
Could you give an example of a symlink?
