### ISSUE TITLE
steal-clone issue in IE9 

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1466] opened 2018-10-05 15:58 UTC
I think, but am unsure, there is a steal-clone issue in IE9.

This can be seen by cloning `canjs/can-types` and running its tests in IE9.  The test __can-types: should throw if can-namespace.types is already defined__ will fail.

![image](https://user-images.githubusercontent.com/78602/46545800-f5d2a700-c88c-11e8-816e-20be5036496d.png)

The test tries to reload `can-types` with `types` already defined and see that the `import()` is rejected:

```js
QUnit.test('should throw if can-namespace.types is already defined', function() {
	stop();
	clone({
		'can-namespace': {
			"default": {
				types: {}
			},
			__useDefault: true
		}
	})
	.import('./can-types')
	.then(function() {
		ok(false, 'should throw');
		start();
	})
	.catch(function(err) {
		var errMsg = err && err.message || err;
		ok(errMsg.indexOf('can-types') >= 0, 'should throw an error about can-types');
		start();
	});
});
```

The import is __NOT__ rejected. It is resolved and the test fails.

__CURIOUSLY__, the error is thrown as `clone` seems to be injecting a new `namespace`.  A debugger (or console.log), will be hit here in `can-types.js`

```js
if (namespace.types) {
        debugger;
	throw new Error("You can't have two versions of can-types, check your dependencies");
} else {
	module.exports = namespace.types = types;
}
```

The error is caught and seemingly handled right up to `doDynamicExecute` where `linkError` is called. Within `linkError` it even seems to be rejecting a deferred like linkSet thing.

```js
function doDynamicExecute(linkSet, load, linkError) {
    try {
      var module = load.execute();
    }
    catch(e) {
      linkError(load, e);
      return;
    }
    if (!module || !(module instanceof Module))
      linkError(load, new TypeError('Execution must define a Module instance'));
    else
      return module;
  }
```

After this point, I gave up :-).

**Comment by justinbmeyer** [comment] 2018-10-05 16:02
In `unsuccessful` hopes to simplify the problem, I tried using `System.import` directly:

```js
System.import("can-types/weird").then(function(){
 console.log("worked")
}, function(){ 
  console.log("borked")
})
```

Where `weird` looks like:

```js
console.log("weird");
throw new Error("I DON'T WORK");
```

This produced expected results:

```
LOG: weird 
LOG: borked 
```

**Comment by matthewp** [comment] 2018-10-05 16:04
Is there a branch where I can see this problem occurring?

**Comment by justinbmeyer** [comment] 2018-10-05 16:10
it's the master branch.

**Comment by matthewp** [comment] 2018-10-05 16:17
The master branch of canjs? That doesn't support IE9...

**Comment by justinbmeyer** [comment] 2018-10-05 16:29
As noted above:

> This can be seen by cloning canjs/can-types

**Comment by matthewp** [comment] 2018-10-05 16:57
Ok thanks.

**Comment by matthewp** [comment] 2018-10-05 18:02
The problem is with the error, not with steal-clone. I think this is behaving correctly but the assertion is expecting a certain error message.

The problem seems to be that the code-frame plugin we use (the thing that pretty-prints source code) doesn't work in IE9. Going to quickly see if that can be fixed.

**Comment by matthewp** [comment] 2018-10-05 18:02
Well, first going to verify that the test will pass once this is bypassed.

**Comment by matthewp** [comment] 2018-10-05 18:04
Yeah that's the problem. Given that I can likely isolate the problem further...

**Comment by matthewp** [comment] 2018-10-05 18:17
Looks the specific problem with IE is that babel-code-frame depends on `__proto__` and IE9 doesn't support that. So we can just check for that support.

**Comment by matthewp** [comment] 2018-10-05 18:55
This is fixed in https://github.com/stealjs/steal/releases/tag/v1.12.6. I just ran can-types tests and they pass in IE9.

**Closed by matthewp** 2018-10-05 18:55 UTC
Labels: bug, error messages
