### ISSUE TITLE
Meta deps not being normalized by npm extension

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1104] opened 2017-03-17 17:55 UTC
https://github.com/m-mujica/steal-meta-deps-npm

```json
 "meta": {
    "justifiedGallery/src/js/justifiedGallery": {
      "format": "global",
        "deps": [
          "jquery",
          "justifiedGallery/src/less/justifiedGallery.less"
       ]
    }
}
```

I'm getting `GET http://localhost:8080/jquery.js 404 (Not Found)`, Steal should be looking for jquery in the node_modules folder.

**Comment by m-mujica** [comment] 2017-03-20 14:50
`justifiedGallery` does not define jquery as a dependency in its package.json.

Steal is normalising the `load.metadata.deps` using `justifiedGallery` as its parent module and since its package.json is missing the jquery dependency entry, the npm extension "thinks" it's a regular module. 

wondering if there is anything we can do in Steal to handle this, or if we should care about this at all. (cc: @matthewp)

We could modify the progressive loading guide to use the full path to node_modules folder instead @justinbmeyer 

```json
 "meta": {
    "justifiedGallery/src/js/justifiedGallery": {
      "format": "global",
        "deps": [
          "node_modules/jquery/dist/jquery.js",
          "justifiedGallery/src/less/justifiedGallery.less"
       ]
    }
}
```

thoughts?

**Comment by matthewp** [comment] 2017-03-21 16:17
I think the bug here is that it is using `justifiedGallery` as the parent. The parent should be the package where this configuration is defined.

**Comment by m-mujica** [comment] 2017-03-21 16:18
@matthewp gotcha, I'll look into it.

**Comment by m-mujica** [comment] 2017-03-21 16:32
@matthewp so the change should be around here:

https://github.com/stealjs/steal/blob/8c0c2239c54aba8c98677e126164d4d95f21e452/steal.js#L4002

I could pass `loader.configMain` instead of `load.name` as the parent. Is it safe to assume all module names in `load.metadata.deps` need to be normalized against the `configMain`?

**Comment by m-mujica** [comment] 2017-03-21 16:38
Also I wrote this test https://github.com/stealjs/steal/pull/1110

**Comment by matthewp** [comment] 2017-03-21 17:18
> @matthewp so the change should be around here:

We talked about this offline but for record, this is not the solution. The solution is to update npm-convert to handle meta.deps.

**Comment by matthewp** [comment] 2017-03-21 17:56
This is a dupe of https://github.com/stealjs/steal/issues/971

**Closed by matthewp** 2017-03-21 17:56 UTC
Labels: bug
