### ISSUE TITLE
Steal is unable to load Babel

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal#375] opened 2015-04-07 06:26 UTC
A simple [gist](https://gist.github.com/BigAB/0aa361fd28c033f2160e/bd0470703ed3ba972ecc56748e48443a9996e69a) 

You can see this working, and it *seems* to be using Babel for transpiling.

![screen shot 2015-04-07 at 1 20 55 am](https://cloud.githubusercontent.com/assets/76821/7017963/80213f10-dcc4-11e4-8ac0-d3f5088e8f86.png)

Then do `npm install --save-dev babel` and it breaks:
[breaking gist](https://gist.github.com/BigAB/0aa361fd28c033f2160e)

![screen shot 2015-04-07 at 1 19 11 am](https://cloud.githubusercontent.com/assets/76821/7017935/3241808e-dcc4-11e4-9383-32f6e726508c.png)

If it is helpful at all here is the puke-of-errors:

```
Live reload enabled.
steal.js:2606 GET http://localhost:8080/fs.js 404 (Not Found)
steal.js:5502 error Error loading "main" at http://localhost:8080/main.js
Error loading "fs" at http://localhost:8080/fs.js
Error loading "fs" from "babel@5.0.9#index" at http://localhost:8080/node_modules/babel/index.js
Not Found: http://localhost:8080/fs.js undefined
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/transformation.js 404 (Not Found)
steal.js:140 Potentially unhandled rejection [7] Error loading "main" at http://localhost:8080/main.js
Error loading "fs" at http://localhost:8080/fs.js
Error loading "fs" from "babel@5.0.9#index" at http://localhost:8080/node_modules/babel/index.js
Not Found: http://localhost:8080/fs.js (WARNING: non-Error used)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/acorn.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/options.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/traversal.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/package.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/types.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/module.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/path.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/fs.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/util.js 404 (Not Found)
3steal.js:1490 Assertion failed: loading or loaded
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/traversal.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/types.js 404 (Not Found)
steal.js:1490 Assertion failed: loading or loaded
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/acorn.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/generation.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/babel-runtime/package.js 404 (Not Found)
6steal.js:1490 Assertion failed: loading or loaded
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/package.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/transformation.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/options.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/tty.js 404 (Not Found)
steal.js:2606 GET http://localhost:8080/net.js 404 (Not Found)
steal.js:1490 Assertion failed: loading or loaded
steal.js:2606 GET http://localhost:8080/os.js 404 (Not Found)
steal.js:1490 Assertion failed: loading or loaded
steal.js:2606 GET http://localhost:8080/assert.js 404 (Not Found)
2steal.js:1490 Assertion failed: loading or loaded
```

**Comment by matthewp** [comment] 2015-04-07 13:09
Your gist is 404ing.  But I think I know what is going on here, to use babel is loads `babel` and since that's also an npm package it gets overwritten. You should be able to fix it locally by adding "babel" to your `npmIgnore` array.  Not sure what the better fix is for this.

**Comment by matthewp** [comment] 2015-04-07 13:12
Actually you can probably use your installed babel instead of the packaged one. Would take some configuration, looks like it is currently loading the node version.

**Comment by matthewp** [comment] 2016-01-20 14:43
Retitled this and changed it to a bug because Steal *should* be able to load the NPM Babel. https://github.com/stealjs/system-npm/issues/3 is likely the root cause.

**Comment by matthewp** [comment] 2016-10-19 14:32
Going to circle back and see if this works. Just for the sake of creating new bugs.

**Comment by matthewp** [comment] 2016-10-21 14:49
# Issues

* [ ] - Object.defineProperty(module, 'exports', { - https://github.com/stealjs/steal/issues/880
* [ ] - process.argv - https://github.com/stealjs/steal-npm/issues/189

At this point it started throwing for code reasons, so I'm guessing that means it has loaded at this point but is unable to actually do a transform.

Going to close this for now, will reopen if more specific issues are discovered.

**Closed by matthewp** 2016-10-21 14:49 UTC
Labels: bug, P3
